version: '3.1'

services:

  migration-to-contentful:
    build: migration_scripts
    image: b2bportalregistry.azurecr.io/b2b-portal-migration-to-contentful:1.4.1
    environment:
      SYNC_BASIC_AUTH_PASSWORD
      SYNC_BASIC_AUTH_USER
      SYNC_CONTENTFUL_API_KEY
      SYNC_CONTENTFUL_ENVIRONMENT
      SYNC_CONTENTFUL_SPACE_ID
      SYNC_HOST
      SYNC_DEBUG
      SYNC_RICH_TEXT_CONVERTER_URL
    networks:
      - app_net
    ports:
      - 80:5000

  html-to-rich-text:
    build: html-to-rich-text
    image: b2bportalregistry.azurecr.io/b2b-portal-html-to-rich-text:latest
    networks:
      app_net:
        aliases:
          - converter
    ports:
      - 3000:3000

networks:
  app_net: