import os

CTFL_MGMT_API_KEY = os.environ['SYNC_CONTENTFUL_API_KEY']
CTFL_SPACE_ID = os.environ['SYNC_CONTENTFUL_SPACE_ID']
CTFL_ENV_ID = os.environ['SYNC_CONTENTFUL_ENVIRONMENT']
DEFAULT_LOCALE = 'en-US'